import {Inter} from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";

 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} `}
      >
        
        <Layout propsChildren={children} />
      </body>
    </html>
  );
}
